-- ============================================
-- 🚀 SCRIPT COMPLETO DE MIGRAÇÃO DO SUPABASE
-- Sistema de Agendamentos + Loja
-- ============================================
-- 
-- Este script cria TODA a estrutura do banco de dados em uma nova conta Supabase.
-- Execute este script COMPLETO no SQL Editor do Supabase.
-- 
-- Versão: 2.0
-- Data: 2025
-- ============================================

-- ============================================
-- PARTE 1: LIMPEZA INICIAL
-- ============================================
-- Remove estruturas antigas se existirem (para evitar conflitos)

DROP VIEW IF EXISTS info_loja_public CASCADE;
DROP TABLE IF EXISTS customer_auth CASCADE;

-- ============================================
-- PARTE 2: ENUMS
-- ============================================

-- Enum para status de agendamentos
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_agendamento_robusto') THEN
        CREATE TYPE status_agendamento_robusto AS ENUM (
            'AGENDADO',
            'REAGENDADO',
            'CANCELADO',
            'CONCLUÍDO'
        );
    END IF;
END$$;

-- Enum para roles de usuário
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'app_role') THEN
        CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');
    END IF;
END$$;

-- ============================================
-- PARTE 3: TABELAS PRINCIPAIS
-- ============================================

-- 3.1 Tabela: info_loja
-- Armazena informações da loja/estabelecimento
CREATE TABLE IF NOT EXISTS public.info_loja (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    address TEXT,
    opening_time TIME WITHOUT TIME ZONE NOT NULL DEFAULT '09:00:00',
    closing_time TIME WITHOUT TIME ZONE NOT NULL DEFAULT '18:00:00',
    slot_interval_minutes INTEGER NOT NULL DEFAULT 60,
    nome_profissionais TEXT,
    escolha_serviços TEXT,
    instructions TEXT,
    auth_user TEXT,
    url_insta TEXT,
    maps_url TEXT,
    url_phone TEXT
);

-- 3.2 Tabela: feriados
-- Armazena feriados para bloquear agendamentos
CREATE TABLE IF NOT EXISTS public.feriados (
    data DATE NOT NULL PRIMARY KEY,
    descricao TEXT NOT NULL
);

-- 3.3 Tabela: cadastro
-- Armazena cadastro de clientes
CREATE TABLE IF NOT EXISTS public.cadastro (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    user_id UUID,
    nome TEXT NOT NULL,
    contato TEXT NOT NULL,
    data_nascimento TEXT NOT NULL,
    serviços_preferidos TEXT NOT NULL
);

-- 3.4 Tabela: agendamentos_robustos
-- Armazena todos os agendamentos do sistema
CREATE TABLE IF NOT EXISTS public.agendamentos_robustos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    "DATA" DATE NOT NULL,
    "HORA" TIME WITHOUT TIME ZONE NOT NULL,
    "STATUS" status_agendamento_robusto DEFAULT 'AGENDADO'::status_agendamento_robusto,
    "NOME" TEXT,
    "CONTATO" TEXT,
    "PROFISSIONAL" TEXT,
    servico TEXT,
    senha TEXT,
    finalização TEXT
);

-- 3.5 Tabela: bd_ativo
-- Controle interno do sistema
CREATE TABLE IF NOT EXISTS public.bd_ativo (
    id BIGINT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    num BIGINT
);

-- 3.6 Tabela: user_roles
-- Armazena roles de usuários (admin, user, etc.)
CREATE TABLE IF NOT EXISTS public.user_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    role app_role NOT NULL DEFAULT 'user'::app_role,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE (user_id, role)
);

-- 3.7 Tabela: categorias_produto
-- Categorias de produtos da loja
CREATE TABLE IF NOT EXISTS public.categorias_produto (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL UNIQUE,
    ordem INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3.8 Tabela: produtos_loja
-- Produtos da loja
CREATE TABLE IF NOT EXISTS public.produtos_loja (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL,
    preco TEXT NOT NULL,
    foto_url TEXT,
    categoria_id UUID REFERENCES public.categorias_produto(id),
    quantidade INTEGER NOT NULL DEFAULT 0,
    ordem INTEGER DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ============================================
-- PARTE 4: ÍNDICES
-- ============================================

-- Índices para melhorar performance de consultas
CREATE INDEX IF NOT EXISTS idx_agendamentos_data ON public.agendamentos_robustos("DATA");
CREATE INDEX IF NOT EXISTS idx_agendamentos_status ON public.agendamentos_robustos("STATUS");
CREATE INDEX IF NOT EXISTS idx_agendamentos_data_hora ON public.agendamentos_robustos("DATA", "HORA");

-- ============================================
-- PARTE 5: FUNÇÕES
-- ============================================

-- 5.1 Função para verificar se usuário é admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.user_roles
        WHERE user_id = auth.uid()
        AND role = 'admin'
    )
$$;

-- 5.2 Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- 5.3 Função para atualizar updated_at em produtos
CREATE OR REPLACE FUNCTION public.update_produtos_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- ============================================
-- PARTE 6: TRIGGERS
-- ============================================

-- Trigger para atualizar updated_at em produtos
DROP TRIGGER IF EXISTS update_produtos_updated_at ON public.produtos_loja;
CREATE TRIGGER update_produtos_updated_at
    BEFORE UPDATE ON public.produtos_loja
    FOR EACH ROW
    EXECUTE FUNCTION public.update_produtos_updated_at();

-- ============================================
-- PARTE 7: ROW LEVEL SECURITY (RLS)
-- ============================================

-- 7.1 Habilitar RLS em todas as tabelas
ALTER TABLE public.info_loja ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feriados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cadastro ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agendamentos_robustos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bd_ativo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias_produto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produtos_loja ENABLE ROW LEVEL SECURITY;

-- ============================================
-- PARTE 8: POLÍTICAS RLS
-- ============================================

-- 8.1 Políticas para info_loja
DROP POLICY IF EXISTS "Public can read info_loja" ON public.info_loja;
DROP POLICY IF EXISTS "Service role can insert info_loja" ON public.info_loja;
DROP POLICY IF EXISTS "Service role can update info_loja" ON public.info_loja;
DROP POLICY IF EXISTS "Service role can delete info_loja" ON public.info_loja;

CREATE POLICY "Public can read info_loja"
    ON public.info_loja FOR SELECT
    USING (true);

CREATE POLICY "Service role can insert info_loja"
    ON public.info_loja FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Service role can update info_loja"
    ON public.info_loja FOR UPDATE
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Service role can delete info_loja"
    ON public.info_loja FOR DELETE
    USING (true);

-- 8.2 Políticas para feriados
DROP POLICY IF EXISTS "Public can read feriados" ON public.feriados;
DROP POLICY IF EXISTS "Service role full access to feriados" ON public.feriados;

CREATE POLICY "Public can read feriados"
    ON public.feriados FOR SELECT
    USING (true);

CREATE POLICY "Service role full access to feriados"
    ON public.feriados FOR ALL
    USING (true)
    WITH CHECK (true);

-- 8.3 Políticas para cadastro
DROP POLICY IF EXISTS "Admins can read all cadastros" ON public.cadastro;
DROP POLICY IF EXISTS "Service role full access cadastro" ON public.cadastro;

CREATE POLICY "Service role full access cadastro"
    ON public.cadastro FOR ALL
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Admins can read all cadastros"
    ON public.cadastro FOR SELECT
    USING (is_admin());

-- 8.4 Políticas para agendamentos_robustos
DROP POLICY IF EXISTS "Admins can read all appointments" ON public.agendamentos_robustos;
DROP POLICY IF EXISTS "Service role full access appointments" ON public.agendamentos_robustos;

CREATE POLICY "Service role full access appointments"
    ON public.agendamentos_robustos FOR ALL
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Admins can read all appointments"
    ON public.agendamentos_robustos FOR SELECT
    USING (is_admin());

-- 8.5 Políticas para bd_ativo
DROP POLICY IF EXISTS "Service role full access bd_ativo" ON public.bd_ativo;

CREATE POLICY "Service role full access bd_ativo"
    ON public.bd_ativo FOR ALL
    USING (true)
    WITH CHECK (true);

-- 8.6 Políticas para user_roles
DROP POLICY IF EXISTS "Users can read own roles" ON public.user_roles;
DROP POLICY IF EXISTS "Service role manages roles" ON public.user_roles;

CREATE POLICY "Users can read own roles"
    ON public.user_roles FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Service role manages roles"
    ON public.user_roles FOR ALL
    USING (true)
    WITH CHECK (true);

-- 8.7 Políticas para categorias_produto
DROP POLICY IF EXISTS "Public can read categories" ON public.categorias_produto;
DROP POLICY IF EXISTS "Admins can insert categories" ON public.categorias_produto;
DROP POLICY IF EXISTS "Admins can update categories" ON public.categorias_produto;
DROP POLICY IF EXISTS "Admins can delete categories" ON public.categorias_produto;

CREATE POLICY "Public can read categories"
    ON public.categorias_produto FOR SELECT
    USING (true);

CREATE POLICY "Admins can insert categories"
    ON public.categorias_produto FOR INSERT
    WITH CHECK (is_admin());

CREATE POLICY "Admins can update categories"
    ON public.categorias_produto FOR UPDATE
    USING (is_admin())
    WITH CHECK (is_admin());

CREATE POLICY "Admins can delete categories"
    ON public.categorias_produto FOR DELETE
    USING (is_admin());

-- 8.8 Políticas para produtos_loja
DROP POLICY IF EXISTS "Public can read active products" ON public.produtos_loja;
DROP POLICY IF EXISTS "Admins can read all products" ON public.produtos_loja;
DROP POLICY IF EXISTS "Admins can insert products" ON public.produtos_loja;
DROP POLICY IF EXISTS "Admins can update products" ON public.produtos_loja;
DROP POLICY IF EXISTS "Admins can delete products" ON public.produtos_loja;

CREATE POLICY "Public can read active products"
    ON public.produtos_loja FOR SELECT
    USING (ativo = true);

CREATE POLICY "Admins can read all products"
    ON public.produtos_loja FOR SELECT
    USING (is_admin());

CREATE POLICY "Admins can insert products"
    ON public.produtos_loja FOR INSERT
    WITH CHECK (is_admin());

CREATE POLICY "Admins can update products"
    ON public.produtos_loja FOR UPDATE
    USING (is_admin())
    WITH CHECK (is_admin());

CREATE POLICY "Admins can delete products"
    ON public.produtos_loja FOR DELETE
    USING (is_admin());

-- ============================================
-- PARTE 9: STORAGE BUCKETS
-- ============================================

-- Criar bucket para produtos (se não existir)
INSERT INTO storage.buckets (id, name, public)
VALUES ('produtos', 'produtos', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas de storage para produtos
DROP POLICY IF EXISTS "Public read produtos" ON storage.objects;
DROP POLICY IF EXISTS "Admins can upload produtos" ON storage.objects;
DROP POLICY IF EXISTS "Admins can update produtos" ON storage.objects;
DROP POLICY IF EXISTS "Admins can delete produtos" ON storage.objects;

CREATE POLICY "Public read produtos"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'produtos');

CREATE POLICY "Admins can upload produtos"
    ON storage.objects FOR INSERT
    WITH CHECK (bucket_id = 'produtos' AND (SELECT is_admin()));

CREATE POLICY "Admins can update produtos"
    ON storage.objects FOR UPDATE
    USING (bucket_id = 'produtos' AND (SELECT is_admin()));

CREATE POLICY "Admins can delete produtos"
    ON storage.objects FOR DELETE
    USING (bucket_id = 'produtos' AND (SELECT is_admin()));

-- ============================================
-- PARTE 10: DADOS INICIAIS
-- ============================================

-- 10.1 Inserir dados da loja (ALTERE ESTES VALORES)
DELETE FROM public.info_loja;
INSERT INTO public.info_loja (
    name,
    address,
    opening_time,
    closing_time,
    slot_interval_minutes,
    nome_profissionais,
    escolha_serviços,
    auth_user,
    url_insta,
    maps_url,
    url_phone
) VALUES (
    'Nome da Barbearia',           -- ALTERE: Nome da loja
    'Endereço completo',           -- ALTERE: Endereço
    '08:00:00',                    -- ALTERE: Horário de abertura
    '21:00:00',                    -- ALTERE: Horário de fechamento
    60,                            -- Intervalo em minutos
    E'PROFISSIONAL 1\nPROFISSIONAL 2',  -- ALTERE: Lista de profissionais
    E'Cabelo + Barba\nCabelo\nBarba',    -- ALTERE: Serviços oferecidos
    'admin@email.com',              -- ALTERE: Email do admin
    'https://instagram.com/sua_loja', -- ALTERE: URL do Instagram
    'https://maps.google.com/link',   -- ALTERE: URL do Google Maps
    '+5511999999999'                  -- ALTERE: Telefone
);

-- 10.2 Inserir categorias padrão
INSERT INTO public.categorias_produto (nome, ordem) VALUES
    ('Cabelo', 1),
    ('Barba', 2)
ON CONFLICT (nome) DO NOTHING;

-- 10.3 Inserir feriados nacionais 2025-2026
DELETE FROM public.feriados;
INSERT INTO public.feriados (data, descricao) VALUES
    -- 2025
    ('2025-01-01', 'Confraternização Universal'),
    ('2025-02-28', 'Carnaval'),
    ('2025-03-03', 'Segunda-feira de Carnaval'),
    ('2025-03-04', 'Terça-feira de Carnaval'),
    ('2025-04-18', 'Sexta-feira Santa'),
    ('2025-04-20', 'Páscoa'),
    ('2025-04-21', 'Tiradentes'),
    ('2025-05-01', 'Dia do Trabalhador'),
    ('2025-06-19', 'Corpus Christi'),
    ('2025-09-07', 'Independência do Brasil'),
    ('2025-10-12', 'Nossa Senhora Aparecida'),
    ('2025-11-02', 'Finados'),
    ('2025-11-15', 'Proclamação da República'),
    ('2025-11-20', 'Dia da Consciência Negra'),
    ('2025-12-25', 'Natal'),
    -- 2026
    ('2026-01-01', 'Confraternização Universal'),
    ('2026-02-13', 'Carnaval'),
    ('2026-02-16', 'Segunda-feira de Carnaval'),
    ('2026-02-17', 'Terça-feira de Carnaval'),
    ('2026-04-03', 'Sexta-feira Santa'),
    ('2026-04-05', 'Páscoa'),
    ('2026-04-21', 'Tiradentes'),
    ('2026-05-01', 'Dia do Trabalhador'),
    ('2026-06-04', 'Corpus Christi'),
    ('2026-09-07', 'Independência do Brasil'),
    ('2026-10-12', 'Nossa Senhora Aparecida'),
    ('2026-11-02', 'Finados'),
    ('2026-11-15', 'Proclamação da República'),
    ('2026-11-20', 'Dia da Consciência Negra'),
    ('2026-12-25', 'Natal');

-- ============================================
-- PARTE 11: VERIFICAÇÃO FINAL
-- ============================================

-- Verificar se RLS está ativo em todas as tabelas
SELECT 
    schemaname, 
    tablename, 
    rowsecurity as rls_enabled
FROM pg_tables
WHERE schemaname = 'public'
AND tablename IN (
    'info_loja', 
    'feriados', 
    'cadastro', 
    'agendamentos_robustos', 
    'bd_ativo',
    'user_roles',
    'categorias_produto',
    'produtos_loja'
)
ORDER BY tablename;

-- ============================================
-- 📋 PRÓXIMOS PASSOS (MANUAL)
-- ============================================
/*
1. CRIAR USUÁRIO ADMIN no Supabase Auth:
   - Vá em Authentication > Users
   - Clique em "Add user"
   - Email: MESMO email usado em auth_user acima
   - Senha: Crie uma senha segura
   - Clique em "Create User"

2. ADICIONAR ROLE DE ADMIN para o usuário:
   - Vá em SQL Editor
   - Execute (substitua o UUID do usuário):
   
   INSERT INTO public.user_roles (user_id, role)
   VALUES ('UUID-DO-USUARIO-CRIADO', 'admin');

3. DEPLOY DAS EDGE FUNCTIONS:
   - Veja a documentação REPLICAÇÃOV2.md

4. CONFIGURAR VARIÁVEIS DE AMBIENTE no frontend:
   - VITE_SUPABASE_URL
   - VITE_SUPABASE_ANON_KEY
*/
