-- =========================================
-- SCRIPT PARA CRIAÇÃO DE TODAS AS TABELAS
-- Sistema de Agendamentos
-- =========================================

-- Este script cria todas as tabelas necessárias para o sistema de agendamentos
-- Execute este script em um projeto Supabase novo

-- =========================================
-- 1. ENUM para Status de Agendamentos
-- =========================================

CREATE TYPE status_agendamento_robusto AS ENUM (
  'AGENDADO',
  'REAGENDADO',
  'CANCELADO',
  'CONCLUÍDO'
);

-- =========================================
-- 2. TABELA: info_loja
-- Armazena informações da loja/estabelecimento
-- =========================================

CREATE TABLE public.info_loja (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  maps_url TEXT,
  opening_time TIME WITHOUT TIME ZONE NOT NULL DEFAULT '09:00:00',
  closing_time TIME WITHOUT TIME ZONE NOT NULL DEFAULT '18:00:00',
  slot_interval_minutes INTEGER NOT NULL DEFAULT 60,
  nome_profissionais TEXT,
  escolha_serviços TEXT,
  instructions TEXT,
  auth_user TEXT
);

-- =========================================
-- 3. TABELA: feriados
-- Armazena feriados para bloquear agendamentos
-- =========================================

CREATE TABLE public.feriados (
  data DATE NOT NULL PRIMARY KEY,
  descricao TEXT NOT NULL
);

-- =========================================
-- 4. TABELA: cadastro
-- Armazena cadastro de clientes
-- =========================================

CREATE TABLE public.cadastro (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  user_id UUID,
  nome TEXT NOT NULL,
  contato TEXT NOT NULL,
  data_nascimento TEXT NOT NULL,
  serviços_preferidos TEXT NOT NULL
);

-- =========================================
-- 5. TABELA: agendamentos_robustos
-- Armazena todos os agendamentos do sistema
-- =========================================

CREATE TABLE public.agendamentos_robustos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "DATA" DATE NOT NULL,
  "HORA" TIME WITHOUT TIME ZONE NOT NULL,
  "STATUS" status_agendamento_robusto DEFAULT 'AGENDADO'::status_agendamento_robusto,
  "NOME" TEXT,
  "CONTATO" TEXT,
  "PROFISSIONAL" TEXT,
  servico TEXT,
  senha TEXT,
  finalização TEXT
);

-- =========================================
-- 6. TABELA: bd_ativo
-- Controle interno do sistema
-- =========================================

CREATE TABLE public.bd_ativo (
  id BIGINT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  num BIGINT
);

-- =========================================
-- 7. ÍNDICES
-- =========================================

-- Índice para melhorar consultas por data em agendamentos
CREATE INDEX idx_agendamentos_data ON public.agendamentos_robustos("DATA");

-- Índice para melhorar consultas por status
CREATE INDEX idx_agendamentos_status ON public.agendamentos_robustos("STATUS");

-- Índice para melhorar consultas por data e hora
CREATE INDEX idx_agendamentos_data_hora ON public.agendamentos_robustos("DATA", "HORA");

-- =========================================
-- 8. ROW LEVEL SECURITY (RLS)
-- =========================================

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.info_loja ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feriados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cadastro ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agendamentos_robustos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bd_ativo ENABLE ROW LEVEL SECURITY;

-- Políticas para info_loja
CREATE POLICY "Public can read stores"
  ON public.info_loja
  FOR SELECT
  USING (true);

CREATE POLICY "Service role can insert info_loja"
  ON public.info_loja
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Service role can update info_loja"
  ON public.info_loja
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role can delete info_loja"
  ON public.info_loja
  FOR DELETE
  USING (true);

-- Políticas para feriados
CREATE POLICY "Public can read feriados"
  ON public.feriados
  FOR SELECT
  USING (true);

CREATE POLICY "Service role full access to feriados"
  ON public.feriados
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Políticas para cadastro
CREATE POLICY "Authenticated users can read all cadastros"
  ON public.cadastro
  FOR SELECT
  USING (true);

CREATE POLICY "Service role full access to cadastro"
  ON public.cadastro
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Políticas para agendamentos_robustos
CREATE POLICY "Authenticated users can read all appointments"
  ON public.agendamentos_robustos
  FOR SELECT
  USING (true);

CREATE POLICY "Service role can insert appointments"
  ON public.agendamentos_robustos
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Service role can update appointments"
  ON public.agendamentos_robustos
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role can delete appointments"
  ON public.agendamentos_robustos
  FOR DELETE
  USING (true);

-- Políticas para bd_ativo
CREATE POLICY "Service role full access to bd_ativo"
  ON public.bd_ativo
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- =========================================
-- 9. FUNÇÕES
-- =========================================

-- Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- =========================================
-- VERIFICAÇÃO FINAL
-- =========================================

-- Verificar se RLS está ativo em todas as tabelas
SELECT schemaname, tablename, rowsecurity
FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN ('info_loja', 'feriados', 'cadastro', 'agendamentos_robustos', 'bd_ativo')
ORDER BY tablename;

-- =========================================
-- INSTRUÇÕES DE USO
-- =========================================

/*
APÓS EXECUTAR ESTE SCRIPT:

1. Popular a tabela info_loja com os dados da sua loja
   (use o script supabase_setup_instructions.sql)

2. Popular a tabela feriados com os feriados do ano
   (use o script supabase_setup_instructions.sql)

3. Criar um usuário admin no Supabase Auth
   - Vá em Authentication > Users
   - Clique em "Add user"
   - Preencha email e senha
   - Este usuário poderá acessar o Dashboard

4. As Edge Functions do sistema já estão configuradas para usar estas tabelas

5. Verificar se todas as políticas RLS estão ativas executando:
   SELECT * FROM pg_policies WHERE schemaname = 'public';
*/
